### ISSUE TITLE
Outputs "D'oh! Don't know that option!" Every Time

### ISSUE THREAD

**Issue by soehlert** [omardelarosa/hubot-simpsons#1]
`hubot: simpsons quote me`
`I don't mind if you pee in the shower, but only if you're taking a shower. -Marge Simpson`
`D'oh! Don't know that option!`

**Comment by omardelarosa** [comment]
@soehlert This repo is no longer being maintained.  Try switching over to [the new version](https://github.com/hubot-scripts/hubot-thesimpsons) that's on npm:

```
npm install hubot-thesimpsons
```
